"""
Agent implementations for the full_recursive pipeline.

Each agent:
1. Builds a prompt from input data
2. Calls Gemini API with appropriate system prompt
3. Parses the JSON response
4. Returns structured output + call log

Ported from kalshi-research-agents TypeScript implementation.
"""

import json
import re
import time
from datetime import datetime
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .prompts import (
    PLANNER_SYSTEM_PROMPT,
    ANALYST_SYSTEM_PROMPT,
    ADVOCATE_YES_SYSTEM_PROMPT,
    ADVOCATE_NO_SYSTEM_PROMPT,
    VERIFIER_SYSTEM_PROMPT,
    SYNTHESIZER_SYSTEM_PROMPT,
)


# =============================================================================
# Data Classes for Agent Outputs
# =============================================================================

@dataclass
class SubQuestion:
    """A sub-question generated by the planner."""
    id: str
    question: str
    priority: str = "medium"
    target_date: Optional[str] = None
    reasoning: Optional[str] = None


@dataclass
class PlannerOutput:
    """Output from the planner agent."""
    market_type: Optional[str] = None
    domain_context: Optional[str] = None
    sub_questions: List[SubQuestion] = field(default_factory=list)
    focus_notes: str = ""
    reasoning: str = ""
    confidence: float = 0.5


@dataclass
class Citation:
    """A source citation."""
    url: str
    title: Optional[str] = None
    author: Optional[str] = None
    outlet: Optional[str] = None
    publish_date: Optional[str] = None
    # Wayback validation fields (populated by WaybackValidator)
    wayback_validated: bool = False
    wayback_earliest: Optional[str] = None  # Earliest archive date (YYYY-MM-DD)
    wayback_suspicious: bool = False  # True if no pre-cutoff snapshot found


@dataclass
class AnswerClaim:
    """An answer to a sub-question."""
    question_id: str
    answer: str
    confidence: float = 0.5
    citations: List[Citation] = field(default_factory=list)
    evidence_summary: str = ""
    reasoning: str = ""
    potential_issues: List[str] = field(default_factory=list)


@dataclass
class AnalystOutput:
    """Output from the analyst agent."""
    answers: List[AnswerClaim] = field(default_factory=list)
    all_sources_used: List[Citation] = field(default_factory=list)
    overall_confidence: float = 0.5
    reasoning: str = ""


@dataclass
class AdvocateEvidence:
    """A piece of evidence from an advocate."""
    claim: str
    source: Citation
    strength: float = 0.5
    reasoning: str = ""


@dataclass
class AdvocateOutput:
    """Output from an advocate agent."""
    position: str  # YES or NO
    core_argument: str = ""
    primary_evidence: List[AdvocateEvidence] = field(default_factory=list)
    historical_precedent: str = ""
    anticipated_counterarguments: List[str] = field(default_factory=list)
    rebuttals: List[str] = field(default_factory=list)
    weakest_point: str = ""
    confidence: float = 0.5
    reasoning: str = ""
    all_sources_used: List[Citation] = field(default_factory=list)


@dataclass
class Issue:
    """An issue identified by the verifier."""
    type: str  # leakage, coverage, logic, bias, gap, contradiction
    severity: str  # critical, major, minor
    description: str
    affected_claims: List[str] = field(default_factory=list)
    recommendation: Optional[str] = None


@dataclass
class DebateAssessment:
    """Assessment of the advocate debate."""
    advocate_yes_strength: float = 0.5
    advocate_yes_strongest_point: str = ""
    advocate_yes_weakest_point: str = ""
    advocate_no_strength: float = 0.5
    advocate_no_strongest_point: str = ""
    advocate_no_weakest_point: str = ""
    winner: str = "TIE"  # YES, NO, or TIE
    reasoning: str = ""


@dataclass
class VerifierOutput:
    """Output from the verifier agent."""
    issues: List[Issue] = field(default_factory=list)
    debate_assessment: Optional[DebateAssessment] = None
    adjusted_confidences: Dict[str, float] = field(default_factory=dict)
    overall_adjusted_confidence: float = 0.5
    missing_evidence_needs: List[str] = field(default_factory=list)
    reasoning: str = ""


@dataclass
class KeyEvidence:
    """Key evidence supporting a prediction."""
    claim: str
    source: str
    weight: float = 0.5


@dataclass
class SynthesizerOutput:
    """Output from the synthesizer agent."""
    prediction: str = ""
    probability: float = 0.5
    confidence: float = 0.5
    decision: str = "COMMIT"  # COMMIT or RETRY
    reasoning: str = ""
    key_evidence: List[KeyEvidence] = field(default_factory=list)
    caveats: List[str] = field(default_factory=list)
    retry_focus: Optional[List[str]] = None


@dataclass
class LLMCallLog:
    """Log of an LLM API call."""
    call_id: str
    agent: str
    timestamp: str
    iteration: int
    latency_ms: int
    tokens_input: int = 0
    tokens_output: int = 0
    cost_estimate_usd: float = 0.0
    raw_response: str = ""
    parse_error: Optional[str] = None


# =============================================================================
# Gemini Client Wrapper
# =============================================================================

class GeminiAgentClient:
    """
    Wrapper for Gemini API calls with grounding support.

    Provides a consistent interface for all agents to call Gemini
    with system prompts and optional Google Search grounding.

    Features:
    - Automatic retry with exponential backoff
    - Cost tracking per call and session
    - Support for Google Search grounding
    """

    # Cost estimates per 1M tokens (rough estimates)
    COST_PER_1M_INPUT = 0.075  # Gemini 2.0 Flash
    COST_PER_1M_OUTPUT = 0.30

    # Retry configuration
    MAX_RETRIES = 3
    INITIAL_BACKOFF_MS = 1000
    MAX_BACKOFF_MS = 30000
    BACKOFF_MULTIPLIER = 2.0

    # Retryable error patterns
    RETRYABLE_ERRORS = [
        "rate limit",
        "quota exceeded",
        "resource exhausted",
        "503",
        "500",
        "timeout",
        "connection",
        "temporarily unavailable",
    ]

    def __init__(
        self,
        api_key: str,
        model: str = "gemini-2.0-flash",
        verbose: bool = False,
        max_retries: int = 3,
    ):
        self.api_key = api_key
        self.model = model
        self.verbose = verbose
        self.max_retries = max_retries
        self._client = None
        self.total_calls = 0
        self.total_retries = 0
        self.total_tokens_input = 0
        self.total_tokens_output = 0
        self.total_cost_usd = 0.0

    def _get_client(self):
        """Lazy-load Gemini client."""
        if self._client is None:
            from google import genai
            self._client = genai.Client(api_key=self.api_key)
        return self._client

    def _is_retryable_error(self, error: Exception) -> bool:
        """Check if an error is retryable."""
        error_str = str(error).lower()
        return any(pattern in error_str for pattern in self.RETRYABLE_ERRORS)

    def _wait_with_backoff(self, attempt: int) -> None:
        """Wait with exponential backoff."""
        backoff_ms = min(
            self.INITIAL_BACKOFF_MS * (self.BACKOFF_MULTIPLIER ** attempt),
            self.MAX_BACKOFF_MS
        )
        # Add jitter (10% randomness)
        import random
        jitter = backoff_ms * 0.1 * random.random()
        wait_time = (backoff_ms + jitter) / 1000.0

        if self.verbose:
            print(f"[Gemini] Retry {attempt + 1}/{self.max_retries}, waiting {wait_time:.1f}s...")

        time.sleep(wait_time)

    def generate(
        self,
        prompt: str,
        system_instruction: str,
        enable_grounding: bool = True,
        temperature: float = 0.7,
    ) -> Tuple[str, Dict[str, Any]]:
        """
        Generate a response from Gemini with automatic retry.

        Args:
            prompt: User prompt
            system_instruction: System prompt for the agent
            enable_grounding: Enable Google Search grounding
            temperature: Temperature for generation

        Returns:
            Tuple of (response_text, metadata_dict)

        Raises:
            Exception: If all retries fail
        """
        from google.genai import types

        client = self._get_client()
        last_error = None

        for attempt in range(self.max_retries + 1):
            try:
                start_time = time.time()

                # Build config
                config = types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    temperature=temperature,
                )

                # Add grounding if enabled
                if enable_grounding:
                    config.tools = [types.Tool(google_search=types.GoogleSearch())]

                # Make the call
                response = client.models.generate_content(
                    model=self.model,
                    contents=prompt,
                    config=config,
                )

                end_time = time.time()
                latency_ms = int((end_time - start_time) * 1000)

                # Extract text
                text = response.text if response.text else ""

                # Try to get token counts from usage metadata
                tokens_input = 0
                tokens_output = 0
                if hasattr(response, 'usage_metadata') and response.usage_metadata:
                    tokens_input = getattr(response.usage_metadata, 'prompt_token_count', 0) or 0
                    tokens_output = getattr(response.usage_metadata, 'candidates_token_count', 0) or 0

                # Update totals
                self.total_calls += 1
                self.total_tokens_input += tokens_input
                self.total_tokens_output += tokens_output

                # Estimate cost
                cost = (tokens_input / 1_000_000 * self.COST_PER_1M_INPUT +
                        tokens_output / 1_000_000 * self.COST_PER_1M_OUTPUT)
                self.total_cost_usd += cost

                metadata = {
                    "latency_ms": latency_ms,
                    "tokens_input": tokens_input,
                    "tokens_output": tokens_output,
                    "cost_estimate_usd": cost,
                    "retries": attempt,
                }

                if self.verbose:
                    retry_info = f" (retry {attempt})" if attempt > 0 else ""
                    print(f"[Gemini] Call {self.total_calls}{retry_info}: {latency_ms}ms, "
                          f"{tokens_input}+{tokens_output} tokens, ${cost:.4f}")

                return text, metadata

            except Exception as e:
                last_error = e
                self.total_retries += 1

                if self.verbose:
                    print(f"[Gemini] Error on attempt {attempt + 1}: {e}")

                # Check if we should retry
                if attempt < self.max_retries and self._is_retryable_error(e):
                    self._wait_with_backoff(attempt)
                else:
                    # Non-retryable error or max retries reached
                    break

        # All retries failed
        raise RuntimeError(f"Gemini API call failed after {self.max_retries + 1} attempts: {last_error}")

    def get_stats(self) -> Dict[str, Any]:
        """Get client usage statistics."""
        return {
            "total_calls": self.total_calls,
            "total_retries": self.total_retries,
            "total_tokens_input": self.total_tokens_input,
            "total_tokens_output": self.total_tokens_output,
            "total_cost_usd": self.total_cost_usd,
            "retry_rate": self.total_retries / max(1, self.total_calls),
        }


# =============================================================================
# JSON Parsing Utilities
# =============================================================================

def extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Extract JSON from text, handling markdown code blocks."""
    # Try to find JSON in markdown code block
    code_block_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
    if code_block_match:
        text = code_block_match.group(1)

    # Find JSON object boundaries
    text = text.strip()
    start_idx = text.find("{")
    end_idx = text.rfind("}")

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        json_str = text[start_idx:end_idx + 1]
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            pass

    return None


def safe_get(d: Dict, *keys, default=None):
    """Safely get nested dictionary values with fallback keys."""
    for key in keys:
        if isinstance(d, dict) and key in d:
            return d[key]
    return default


# =============================================================================
# Agent Implementations
# =============================================================================

def build_planner_prompt(
    market_title: str,
    market_description: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    notable_moves: List[Dict],
    query_budget: int,
    previous_feedback: Optional[str] = None,
) -> str:
    """Build the prompt for the planner agent."""
    start, end = time_range

    prompt = f"""MARKET ANALYSIS REQUEST

Market: {market_title}

MARKET DATA WINDOW:
- Start: {start}
- End: {end}

CRITICAL: RESEARCH CUTOFF DATE IS {research_cutoff}
ALL research must use sources dated BEFORE {research_cutoff}.
We are simulating a prediction made as of {research_cutoff}.
DO NOT use any information that would not have been available on {research_cutoff}.

MARKET DESCRIPTION:
{market_description[:2000]}

NOTABLE PRICE MOVES (significant swings to investigate):
"""

    if notable_moves:
        for m in notable_moves[:5]:
            date = m.get("date", "unknown")
            move_pct = m.get("move_pct", 0) * 100
            prompt += f"- {date}: {move_pct:+.1f}%\n"
    else:
        prompt += "- No significant moves detected\n"

    prompt += f"""
QUERY BUDGET: {query_budget} sub-questions maximum

YOUR TASK:
1. FIRST: Search to identify what TYPE of market this is
2. THEN: Research how similar outcomes have been predicted in the past
3. IDENTIFY: What systematic forecast errors exist in this domain?
4. CREATE: Sub-questions that mix HISTORICAL context with CURRENT evidence
"""

    if previous_feedback:
        prompt += f"""
FEEDBACK FROM PREVIOUS ITERATION (address these gaps):
{previous_feedback}
"""

    prompt += """
Return your analysis as JSON with marketType, domainContext, and subQuestions."""

    return prompt


def parse_planner_response(text: str) -> Optional[PlannerOutput]:
    """Parse planner agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        sub_questions = []
        raw_questions = safe_get(parsed, "subQuestions", "sub_questions", default=[])
        for i, q in enumerate(raw_questions):
            sub_questions.append(SubQuestion(
                id=safe_get(q, "id", default=f"q{i+1}"),
                question=safe_get(q, "question", default=""),
                priority=safe_get(q, "priority", default="medium"),
                target_date=safe_get(q, "targetDate", "target_date"),
                reasoning=safe_get(q, "reasoning"),
            ))

        return PlannerOutput(
            market_type=safe_get(parsed, "marketType", "market_type"),
            domain_context=safe_get(parsed, "domainContext", "domain_context"),
            sub_questions=sub_questions,
            focus_notes=safe_get(parsed, "focusNotes", "focus_notes", default=""),
            reasoning=safe_get(parsed, "reasoning", default=""),
            confidence=safe_get(parsed, "confidence", default=0.5),
        )
    except Exception:
        return None


def run_planner(
    client: GeminiAgentClient,
    market_title: str,
    market_description: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    notable_moves: List[Dict],
    query_budget: int = 5,
    previous_feedback: Optional[str] = None,
    iteration: int = 1,
) -> Tuple[Optional[PlannerOutput], LLMCallLog]:
    """Run the planner agent."""
    prompt = build_planner_prompt(
        market_title, market_description, time_range, research_cutoff,
        notable_moves, query_budget, previous_feedback
    )

    response, metadata = client.generate(
        prompt,
        PLANNER_SYSTEM_PROMPT,
        enable_grounding=True,
        temperature=0.7,
    )

    output = parse_planner_response(response)

    log = LLMCallLog(
        call_id=f"iter{iteration}_planner",
        agent="planner",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata["cost_estimate_usd"],
        raw_response=response[:2000],
        parse_error=None if output else "Failed to parse planner response",
    )

    return output, log


def build_analyst_prompt(
    market_title: str,
    sub_questions: List[SubQuestion],
    time_range: Tuple[str, str],
    research_cutoff: str,
) -> str:
    """Build the prompt for the analyst agent."""
    start, end = time_range

    prompt = f"""RESEARCH TASK

Market: {market_title}
Market Data Window: {start} to {end}

RESEARCH CUTOFF DATE: {research_cutoff}
CRITICAL CONSTRAINT: Only use sources published BEFORE {research_cutoff}.

SUB-QUESTIONS TO RESEARCH:
"""

    for i, q in enumerate(sub_questions):
        prompt += f"{i+1}. [{q.id}] {q.question}\n"
        prompt += f"   Priority: {q.priority}\n"
        if q.target_date:
            prompt += f"   Target date: {q.target_date}\n"
        prompt += "\n"

    prompt += """
For each question:
1. Search for relevant evidence
2. Verify source dates are before cutoff
3. Score source credibility
4. Synthesize findings with confidence

Return your analysis as JSON."""

    return prompt


def parse_analyst_response(text: str) -> Optional[AnalystOutput]:
    """Parse analyst agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        answers = []
        raw_answers = safe_get(parsed, "answers", default=[])
        for a in raw_answers:
            citations = []
            for c in safe_get(a, "citations", default=[]):
                citations.append(Citation(
                    url=safe_get(c, "url", default=""),
                    title=safe_get(c, "title"),
                    author=safe_get(c, "author"),
                    outlet=safe_get(c, "outlet"),
                    publish_date=safe_get(c, "publishDate", "publish_date"),
                ))

            answers.append(AnswerClaim(
                question_id=safe_get(a, "questionId", "question_id", default=""),
                answer=safe_get(a, "answer", default=""),
                confidence=safe_get(a, "confidence", default=0.5),
                citations=citations,
                evidence_summary=safe_get(a, "evidenceSummary", "evidence_summary", default=""),
                reasoning=safe_get(a, "reasoning", default=""),
                potential_issues=safe_get(a, "potentialIssues", "potential_issues", default=[]),
            ))

        all_sources = []
        for s in safe_get(parsed, "allSourcesUsed", "all_sources_used", default=[]):
            all_sources.append(Citation(
                url=safe_get(s, "url", default=""),
                title=safe_get(s, "title"),
            ))

        return AnalystOutput(
            answers=answers,
            all_sources_used=all_sources,
            overall_confidence=safe_get(parsed, "overallConfidence", "overall_confidence", default=0.5),
            reasoning=safe_get(parsed, "reasoning", default=""),
        )
    except Exception:
        return None


def run_analyst(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
) -> Tuple[Optional[AnalystOutput], LLMCallLog]:
    """Run the analyst agent."""
    prompt = build_analyst_prompt(market_title, sub_questions, time_range, research_cutoff)

    response, metadata = client.generate(
        prompt,
        ANALYST_SYSTEM_PROMPT,
        enable_grounding=True,
        temperature=0.5,
    )

    output = parse_analyst_response(response)

    log = LLMCallLog(
        call_id=f"iter{iteration}_analyst",
        agent="analyst",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata["cost_estimate_usd"],
        raw_response=response[:2000],
        parse_error=None if output else "Failed to parse analyst response",
    )

    return output, log


def build_advocate_prompt(
    market_title: str,
    sub_questions: List[SubQuestion],
    position: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
) -> str:
    """Build the prompt for an advocate agent."""
    start, end = time_range

    prompt = f"""MARKET TO ANALYZE
Title: {market_title}

YOUR POSITION: Argue that this market resolves {position}

RESEARCH WINDOW: {start} to {end}
CRITICAL: Research cutoff is {research_cutoff}. You MUST NOT use any sources published after this date.

CONTEXT - Key questions identified by the Planner:
"""

    for i, q in enumerate(sub_questions):
        prompt += f"{i+1}. [{q.priority}] {q.question}\n"

    prompt += f"""
YOUR TASK:
Build the strongest possible case that this market resolves {position}.
- Search for evidence that supports {position}
- Find historical precedents where similar situations resolved {position}
- Anticipate what an advocate for the opposite outcome would argue
- Prepare rebuttals for those counter-arguments
- Be honest about the weakest part of your case

Remember:
- You are BIASED BY DESIGN - that's your job
- But don't fabricate evidence - cite real sources
- Acknowledge your weakest point honestly
- The strongest arguments address the opponent's best points, not straw men

Return your argument as valid JSON."""

    return prompt


def parse_advocate_response(text: str, position: str) -> Optional[AdvocateOutput]:
    """Parse advocate agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        primary_evidence = []
        for e in safe_get(parsed, "primaryEvidence", "primary_evidence", default=[]):
            source_data = safe_get(e, "source", default={})
            source = Citation(
                url=safe_get(source_data, "url", default=safe_get(e, "url", default="")),
                title=safe_get(source_data, "title", default=safe_get(e, "title")),
                author=safe_get(source_data, "author"),
                outlet=safe_get(source_data, "outlet"),
                publish_date=safe_get(source_data, "publishDate", "publish_date"),
            )
            primary_evidence.append(AdvocateEvidence(
                claim=safe_get(e, "claim", default=""),
                source=source,
                strength=safe_get(e, "strength", default=0.5),
                reasoning=safe_get(e, "reasoning", default=""),
            ))

        all_sources = []
        for s in safe_get(parsed, "allSourcesUsed", "all_sources_used", default=[]):
            all_sources.append(Citation(
                url=safe_get(s, "url", default=""),
                title=safe_get(s, "title"),
            ))

        # Also add sources from evidence if allSourcesUsed is empty
        if not all_sources:
            seen_urls = set()
            for e in primary_evidence:
                if e.source.url and e.source.url not in seen_urls:
                    seen_urls.add(e.source.url)
                    all_sources.append(e.source)

        return AdvocateOutput(
            position=safe_get(parsed, "position", default=position),
            core_argument=safe_get(parsed, "coreArgument", "core_argument", default=""),
            primary_evidence=primary_evidence,
            historical_precedent=safe_get(parsed, "historicalPrecedent", "historical_precedent", default=""),
            anticipated_counterarguments=safe_get(parsed, "anticipatedCounterarguments", "anticipated_counterarguments", default=[]),
            rebuttals=safe_get(parsed, "rebuttals", default=[]),
            weakest_point=safe_get(parsed, "weakestPoint", "weakest_point", default=""),
            confidence=safe_get(parsed, "confidence", default=0.5),
            reasoning=safe_get(parsed, "reasoning", default=""),
            all_sources_used=all_sources,
        )
    except Exception:
        return None


def run_advocate(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    position: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
) -> Tuple[Optional[AdvocateOutput], LLMCallLog]:
    """Run an advocate agent (YES or NO)."""
    prompt = build_advocate_prompt(market_title, sub_questions, position, time_range, research_cutoff)

    system_prompt = ADVOCATE_YES_SYSTEM_PROMPT if position == "YES" else ADVOCATE_NO_SYSTEM_PROMPT

    response, metadata = client.generate(
        prompt,
        system_prompt,
        enable_grounding=True,
        temperature=0.7,
    )

    output = parse_advocate_response(response, position)
    agent_type = f"advocate_{position.lower()}"

    log = LLMCallLog(
        call_id=f"iter{iteration}_{agent_type}",
        agent=agent_type,
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata["cost_estimate_usd"],
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse {agent_type} response",
    )

    return output, log


def build_verifier_prompt(
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    advocate_yes_output: Optional[AdvocateOutput],
    advocate_no_output: Optional[AdvocateOutput],
    wayback_context: str = "",
) -> str:
    """Build the prompt for the verifier agent."""
    start, end = time_range
    has_debate = advocate_yes_output and advocate_no_output

    prompt = f"""VERIFICATION {"AND DEBATE JUDGING " if has_debate else ""}TASK

Market: {market_title}
Market Data Window: {start} to {end}

CRITICAL: RESEARCH CUTOFF DATE IS {research_cutoff}
ANY source after {research_cutoff} is a CRITICAL issue (data leakage).

=== NEUTRAL ANALYST FINDINGS ===
Overall Confidence: {analyst_output.overall_confidence:.0%}
Answers:
"""

    for a in analyst_output.answers:
        prompt += f"- [{a.question_id}] {a.answer[:200]}... (confidence: {a.confidence:.0%})\n"

    if has_debate:
        prompt += f"""
=== ADVOCATE FOR YES ===
Core Argument: {advocate_yes_output.core_argument[:300]}...
Confidence: {advocate_yes_output.confidence:.0%}
Weakest Point: {advocate_yes_output.weakest_point[:200]}...

=== ADVOCATE FOR NO ===
Core Argument: {advocate_no_output.core_argument[:300]}...
Confidence: {advocate_no_output.confidence:.0%}
Weakest Point: {advocate_no_output.weakest_point[:200]}...

YOUR TASKS:
1. VERIFY ALL SOURCES from analyst and BOTH advocates
2. VERIFY AUTHOR CREDIBILITY
3. FIND CONTRADICTIONS and search for missing evidence
4. JUDGE THE DEBATE - which advocate has stronger VERIFIED evidence?
5. IDENTIFY GAPS in all analyses
"""
    else:
        prompt += """
YOUR TASKS:
1. Check EVERY source URL - is it dated before the cutoff?
2. Verify author credibility
3. Search for CONTRADICTING evidence
4. Evaluate whether evidence supports conclusions
5. Identify gaps in the analysis
"""

    # Add Wayback validation context if provided
    if wayback_context:
        prompt += f"""
{wayback_context}
"""

    prompt += """
Be thorough and adversarial. Find the weaknesses in EVERYONE's arguments.

Return your verification as JSON."""

    return prompt


def parse_verifier_response(text: str) -> Optional[VerifierOutput]:
    """Parse verifier agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        issues = []
        for i in safe_get(parsed, "issues", default=[]):
            issues.append(Issue(
                type=safe_get(i, "type", default="gap"),
                severity=safe_get(i, "severity", default="minor"),
                description=safe_get(i, "description", default=""),
                affected_claims=safe_get(i, "affectedClaims", "affected_claims", default=[]),
                recommendation=safe_get(i, "recommendation"),
            ))

        debate_assessment = None
        raw_debate = safe_get(parsed, "debateAssessment", "debate_assessment")
        if raw_debate:
            debate_assessment = DebateAssessment(
                advocate_yes_strength=safe_get(raw_debate, "advocateYesStrength", "advocate_yes_strength", default=0.5),
                advocate_yes_strongest_point=safe_get(raw_debate, "advocateYesStrongestPoint", "advocate_yes_strongest_point", default=""),
                advocate_yes_weakest_point=safe_get(raw_debate, "advocateYesWeakestPoint", "advocate_yes_weakest_point", default=""),
                advocate_no_strength=safe_get(raw_debate, "advocateNoStrength", "advocate_no_strength", default=0.5),
                advocate_no_strongest_point=safe_get(raw_debate, "advocateNoStrongestPoint", "advocate_no_strongest_point", default=""),
                advocate_no_weakest_point=safe_get(raw_debate, "advocateNoWeakestPoint", "advocate_no_weakest_point", default=""),
                winner=safe_get(raw_debate, "winner", default="TIE"),
                reasoning=safe_get(raw_debate, "reasoning", default=""),
            )

        adjusted_confidences = {}
        raw_conf = safe_get(parsed, "adjustedConfidences", "adjusted_confidences", default={})
        for k, v in raw_conf.items():
            adjusted_confidences[k] = float(v) if isinstance(v, (int, float)) else 0.5

        return VerifierOutput(
            issues=issues,
            debate_assessment=debate_assessment,
            adjusted_confidences=adjusted_confidences,
            overall_adjusted_confidence=safe_get(parsed, "overallAdjustedConfidence", "overall_adjusted_confidence", default=0.5),
            missing_evidence_needs=safe_get(parsed, "missingEvidenceNeeds", "missing_evidence_needs", default=[]),
            reasoning=safe_get(parsed, "reasoning", default=""),
        )
    except Exception:
        return None


def run_verifier(
    client: GeminiAgentClient,
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    advocate_yes_output: Optional[AdvocateOutput],
    advocate_no_output: Optional[AdvocateOutput],
    iteration: int = 1,
    wayback_context: str = "",
) -> Tuple[Optional[VerifierOutput], LLMCallLog]:
    """Run the verifier agent."""
    prompt = build_verifier_prompt(
        market_title, time_range, research_cutoff,
        analyst_output, advocate_yes_output, advocate_no_output,
        wayback_context=wayback_context,
    )

    response, metadata = client.generate(
        prompt,
        VERIFIER_SYSTEM_PROMPT,
        enable_grounding=True,
        temperature=0.5,
    )

    output = parse_verifier_response(response)

    log = LLMCallLog(
        call_id=f"iter{iteration}_verifier",
        agent="verifier",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata["cost_estimate_usd"],
        raw_response=response[:2000],
        parse_error=None if output else "Failed to parse verifier response",
    )

    return output, log


def build_synthesizer_prompt(
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    verifier_output: VerifierOutput,
    iteration: int,
    max_iterations: int,
    confidence_threshold: float,
) -> str:
    """Build the prompt for the synthesizer agent."""
    start, end = time_range

    prompt = f"""SYNTHESIS TASK

Market: {market_title}
Iteration: {iteration} of {max_iterations}
Confidence Threshold: {confidence_threshold}
Market Data Window: {start} to {end}
Research Cutoff: {research_cutoff}

=== ANALYST FINDINGS ===
Overall Confidence: {analyst_output.overall_confidence:.0%}
"""

    for a in analyst_output.answers[:3]:
        prompt += f"- {a.answer[:200]}...\n"

    prompt += f"""
=== VERIFIER ASSESSMENT ===
Adjusted Confidence: {verifier_output.overall_adjusted_confidence:.0%}
Issues Found: {len(verifier_output.issues)}
"""

    for i in verifier_output.issues[:3]:
        prompt += f"- [{i.severity}] {i.description[:100]}...\n"

    if verifier_output.debate_assessment:
        da = verifier_output.debate_assessment
        prompt += f"""
=== DEBATE RESULTS (IMPORTANT) ===
Advocate YES strength: {da.advocate_yes_strength:.0%}
  - Strongest point: {da.advocate_yes_strongest_point[:100]}...
Advocate NO strength: {da.advocate_no_strength:.0%}
  - Strongest point: {da.advocate_no_strongest_point[:100]}...

DEBATE WINNER: {da.winner}
Reasoning: {da.reasoning[:200]}...

NOTE: The debate winner indicates which side had BETTER VERIFIED EVIDENCE.
Weight this heavily in your prediction direction.
"""

    prompt += f"""
=== DECISION REQUIRED ===
- Verifier's adjusted confidence: {verifier_output.overall_adjusted_confidence:.0%}
- Threshold for commit: {confidence_threshold:.0%}
- Iterations remaining: {max_iterations - iteration}

{
    "Confidence meets threshold - you may COMMIT if reasoning is sound."
    if verifier_output.overall_adjusted_confidence >= confidence_threshold
    else "Confidence below threshold - consider RETRY if there are clear gaps to fill, or COMMIT with caveats if no clear improvement path."
}
"""

    if verifier_output.missing_evidence_needs:
        prompt += f"""
Missing evidence identified:
"""
        for e in verifier_output.missing_evidence_needs[:3]:
            prompt += f"- {e}\n"

    prompt += """
Return your synthesis as JSON with prediction, probability, confidence, and decision (COMMIT or RETRY)."""

    return prompt


def parse_synthesizer_response(text: str) -> Optional[SynthesizerOutput]:
    """Parse synthesizer agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        key_evidence = []
        for ke in safe_get(parsed, "keyEvidence", "key_evidence", default=[]):
            key_evidence.append(KeyEvidence(
                claim=safe_get(ke, "claim", default=""),
                source=safe_get(ke, "source", default=""),
                weight=safe_get(ke, "weight", default=0.5),
            ))

        return SynthesizerOutput(
            prediction=safe_get(parsed, "prediction", default=""),
            probability=safe_get(parsed, "probability", default=0.5),
            confidence=safe_get(parsed, "confidence", default=0.5),
            decision=safe_get(parsed, "decision", default="COMMIT"),
            reasoning=safe_get(parsed, "reasoning", default=""),
            key_evidence=key_evidence,
            caveats=safe_get(parsed, "caveats", default=[]),
            retry_focus=safe_get(parsed, "retryFocus", "retry_focus"),
        )
    except Exception:
        return None


def run_synthesizer(
    client: GeminiAgentClient,
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    verifier_output: VerifierOutput,
    iteration: int,
    max_iterations: int,
    confidence_threshold: float,
) -> Tuple[Optional[SynthesizerOutput], LLMCallLog]:
    """Run the synthesizer agent."""
    prompt = build_synthesizer_prompt(
        market_title, time_range, research_cutoff,
        analyst_output, verifier_output,
        iteration, max_iterations, confidence_threshold
    )

    response, metadata = client.generate(
        prompt,
        SYNTHESIZER_SYSTEM_PROMPT,
        enable_grounding=True,
        temperature=0.5,
    )

    output = parse_synthesizer_response(response)

    log = LLMCallLog(
        call_id=f"iter{iteration}_synthesizer",
        agent="synthesizer",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata["cost_estimate_usd"],
        raw_response=response[:2000],
        parse_error=None if output else "Failed to parse synthesizer response",
    )

    return output, log


# =============================================================================
# LESSONS LEARNED
# =============================================================================
# 2026-01-21 Agent Implementation:
#
# PORTING FROM TYPESCRIPT:
# 1. Simplified dataclasses vs TypeScript interfaces
# 2. Used @dataclass with field(default_factory=list) for mutable defaults
# 3. JSON parsing handles both camelCase and snake_case keys
#
# API INTEGRATION:
# 1. Gemini grounding via google_search tool works well
# 2. Token counts from usage_metadata may be None - handle gracefully
# 3. Temperature: lower (0.5) for analyst/verifier, higher (0.7) for advocates
#
# PROMPT ENGINEERING:
# 1. Cutoff date enforcement is repeated multiple times - works better
# 2. JSON output format must be explicit in prompts
# 3. Examples in prompts help but increase token usage
#
# ERROR HANDLING:
# 1. All parse functions return Optional - caller handles None
# 2. LLMCallLog captures raw response for debugging
# 3. parse_error field tracks parsing failures
#
