"""
Agent implementations for the full_recursive pipeline.

Each agent:
1. Builds a prompt from input data
2. Calls Gemini API with appropriate system prompt
3. Parses the JSON response
4. Returns structured output + call log

Ported from kalshi-research-agents TypeScript implementation.
"""

import json
import re
import time
from datetime import datetime
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple

from .prompts import (
    PLANNER_SYSTEM_PROMPT,
    ANALYST_SYSTEM_PROMPT,
    ADVOCATE_YES_SYSTEM_PROMPT,
    ADVOCATE_NO_SYSTEM_PROMPT,
    VERIFIER_SYSTEM_PROMPT,
    SYNTHESIZER_SYSTEM_PROMPT,
)


# =============================================================================
# Model Pricing Configuration (per 1M tokens)
# =============================================================================

# Pricing as of Jan 2026 - source: https://ai.google.dev/gemini-api/docs/pricing
GEMINI_PRICING = {
    # Gemini 2.0 models
    "gemini-2.0-flash": {"input": 0.10, "output": 0.40},
    "gemini-2.0-flash-lite": {"input": 0.075, "output": 0.30},
    "gemini-2.0-flash-exp": {"input": 0.10, "output": 0.40},
    # Gemini 2.5 models
    "gemini-2.5-pro": {"input": 1.25, "output": 10.00},
    "gemini-2.5-pro-preview": {"input": 1.25, "output": 10.00},
    "gemini-2.5-flash": {"input": 0.15, "output": 0.60},
    "gemini-2.5-flash-lite": {"input": 0.10, "output": 0.40},
    # Gemini 1.5 models (legacy)
    "gemini-1.5-pro": {"input": 1.25, "output": 5.00},
    "gemini-1.5-flash": {"input": 0.075, "output": 0.30},
}

DEFAULT_PRICING = {"input": 0.10, "output": 0.40}


def estimate_tokens_from_text(text: str) -> int:
    """Estimate token count from text (~4 chars/token for English)."""
    if not text:
        return 0
    return max(1, len(text) // 4)


def get_model_pricing(model: str) -> Dict[str, float]:
    """Get pricing for a model, with fallback to default."""
    base_model = model.lower()
    for suffix in ["-001", "-002", "-latest", "-preview"]:
        if base_model.endswith(suffix) and base_model[:-len(suffix)] in GEMINI_PRICING:
            base_model = base_model[:-len(suffix)]
            break
    return GEMINI_PRICING.get(base_model, DEFAULT_PRICING)


# =============================================================================
# Data Classes for Agent Outputs
# =============================================================================

@dataclass
class SubQuestion:
    """A sub-question generated by the planner."""
    id: str
    question: str
    priority: str = "medium"
    target_date: Optional[str] = None
    reasoning: Optional[str] = None


@dataclass
class PlannerOutput:
    """Output from the planner agent."""
    market_type: Optional[str] = None
    domain_context: Optional[str] = None
    sub_questions: List[SubQuestion] = field(default_factory=list)
    focus_notes: str = ""
    reasoning: str = ""
    confidence: float = 0.5


@dataclass
class Citation:
    """A source citation."""
    url: str
    title: Optional[str] = None
    author: Optional[str] = None
    outlet: Optional[str] = None
    publish_date: Optional[str] = None
    # Wayback validation fields (populated by WaybackValidator)
    wayback_validated: bool = False
    wayback_earliest: Optional[str] = None  # Earliest archive date (YYYY-MM-DD)
    wayback_suspicious: bool = False  # True if no pre-cutoff snapshot found


@dataclass
class AnswerClaim:
    """An answer to a sub-question."""
    question_id: str
    answer: str
    confidence: float = 0.5
    citations: List[Citation] = field(default_factory=list)
    evidence_summary: str = ""
    reasoning: str = ""
    potential_issues: List[str] = field(default_factory=list)


@dataclass
class AnalystOutput:
    """Output from the analyst agent."""
    answers: List[AnswerClaim] = field(default_factory=list)
    all_sources_used: List[Citation] = field(default_factory=list)
    overall_confidence: float = 0.5
    reasoning: str = ""


@dataclass
class AdvocateEvidence:
    """A piece of evidence from an advocate."""
    claim: str
    source: Citation
    strength: float = 0.5
    reasoning: str = ""


@dataclass
class AdvocateOutput:
    """Output from an advocate agent."""
    position: str  # YES or NO
    core_argument: str = ""
    primary_evidence: List[AdvocateEvidence] = field(default_factory=list)
    historical_precedent: str = ""
    anticipated_counterarguments: List[str] = field(default_factory=list)
    rebuttals: List[str] = field(default_factory=list)
    weakest_point: str = ""
    confidence: float = 0.5
    reasoning: str = ""
    all_sources_used: List[Citation] = field(default_factory=list)


@dataclass
class Issue:
    """An issue identified by the verifier."""
    type: str  # leakage, coverage, logic, bias, gap, contradiction
    severity: str  # critical, major, minor
    description: str
    affected_claims: List[str] = field(default_factory=list)
    recommendation: Optional[str] = None


@dataclass
class DebateAssessment:
    """Assessment of the advocate debate."""
    advocate_yes_strength: float = 0.5
    advocate_yes_strongest_point: str = ""
    advocate_yes_weakest_point: str = ""
    advocate_no_strength: float = 0.5
    advocate_no_strongest_point: str = ""
    advocate_no_weakest_point: str = ""
    winner: str = "TIE"  # YES, NO, or TIE
    reasoning: str = ""


@dataclass
class VerifierOutput:
    """Output from the verifier agent."""
    issues: List[Issue] = field(default_factory=list)
    debate_assessment: Optional[DebateAssessment] = None
    adjusted_confidences: Dict[str, float] = field(default_factory=dict)
    overall_adjusted_confidence: float = 0.5
    missing_evidence_needs: List[str] = field(default_factory=list)
    reasoning: str = ""


@dataclass
class KeyEvidence:
    """Key evidence supporting a prediction."""
    claim: str
    source: str
    weight: float = 0.5


@dataclass
class SynthesizerOutput:
    """Output from the synthesizer agent."""
    prediction: str = ""
    probability: float = 0.5
    confidence: float = 0.5
    decision: str = "COMMIT"  # COMMIT or RETRY
    reasoning: str = ""
    key_evidence: List[KeyEvidence] = field(default_factory=list)
    caveats: List[str] = field(default_factory=list)
    retry_focus: Optional[List[str]] = None


@dataclass
class LLMCallLog:
    """Log of an LLM API call with accurate token cost tracking."""
    call_id: str
    agent: str
    timestamp: str
    iteration: int
    latency_ms: int
    tokens_input: int = 0
    tokens_output: int = 0
    cost_estimate_usd: float = 0.0  # Calculated cost using model-specific pricing
    raw_response: str = ""
    parse_error: Optional[str] = None
    # Token tracking metadata
    token_source: str = "api"  # "api" if from usage_metadata, "estimated" if fallback
    model: str = ""  # Model used for pricing calculation


# =============================================================================
# Gemini Client Wrapper
# =============================================================================

class GeminiAgentClient:
    """
    Wrapper for Gemini API calls with grounding support.

    Provides a consistent interface for all agents to call Gemini
    with system prompts and optional Google Search grounding.

    Features:
    - Automatic retry with exponential backoff
    - Accurate cost tracking using model-specific pricing
    - Fallback token estimation when API doesn't return usage_metadata
    - Support for Google Search grounding
    """

    # Retry configuration
    MAX_RETRIES = 3
    INITIAL_BACKOFF_MS = 1000
    MAX_BACKOFF_MS = 30000
    BACKOFF_MULTIPLIER = 2.0

    # Retryable error patterns
    RETRYABLE_ERRORS = [
        "rate limit",
        "quota exceeded",
        "resource exhausted",
        "503",
        "500",
        "timeout",
        "connection",
        "temporarily unavailable",
    ]

    def __init__(
        self,
        api_key: str,
        model: str = "gemini-2.0-flash",
        verbose: bool = False,
        max_retries: int = 3,
    ):
        self.api_key = api_key
        self.model = model
        self.verbose = verbose
        self.max_retries = max_retries
        self._client = None
        self.total_calls = 0
        self.total_retries = 0
        # Token tracking - actual from API
        self.total_tokens_input_actual = 0
        self.total_tokens_output_actual = 0
        # Token tracking - estimated (fallback)
        self.total_tokens_input_estimated = 0
        self.total_tokens_output_estimated = 0
        self.total_cost_usd = 0.0
        self.calls_with_actual_tokens = 0
        self.calls_with_estimated_tokens = 0

    def _get_client(self):
        """Lazy-load Gemini client."""
        if self._client is None:
            from google import genai
            self._client = genai.Client(api_key=self.api_key)
        return self._client

    def _is_retryable_error(self, error: Exception) -> bool:
        """Check if an error is retryable."""
        error_str = str(error).lower()
        return any(pattern in error_str for pattern in self.RETRYABLE_ERRORS)

    def _wait_with_backoff(self, attempt: int) -> None:
        """Wait with exponential backoff."""
        backoff_ms = min(
            self.INITIAL_BACKOFF_MS * (self.BACKOFF_MULTIPLIER ** attempt),
            self.MAX_BACKOFF_MS
        )
        # Add jitter (10% randomness)
        import random
        jitter = backoff_ms * 0.1 * random.random()
        wait_time = (backoff_ms + jitter) / 1000.0

        if self.verbose:
            print(f"[Gemini] Retry {attempt + 1}/{self.max_retries}, waiting {wait_time:.1f}s...")

        time.sleep(wait_time)

    def generate(
        self,
        prompt: str,
        system_instruction: str,
        enable_grounding: bool = True,
        temperature: float = 0.7,
    ) -> Tuple[str, Dict[str, Any]]:
        """
        Generate a response from Gemini with automatic retry.

        Args:
            prompt: User prompt
            system_instruction: System prompt for the agent
            enable_grounding: Enable Google Search grounding
            temperature: Temperature for generation

        Returns:
            Tuple of (response_text, metadata_dict)

        Raises:
            Exception: If all retries fail
        """
        from google.genai import types

        client = self._get_client()
        last_error = None

        for attempt in range(self.max_retries + 1):
            try:
                start_time = time.time()

                # Build config
                config = types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    temperature=temperature,
                )

                # Add grounding if enabled
                if enable_grounding:
                    config.tools = [types.Tool(google_search=types.GoogleSearch())]

                # Make the call
                response = client.models.generate_content(
                    model=self.model,
                    contents=prompt,
                    config=config,
                )

                end_time = time.time()
                latency_ms = int((end_time - start_time) * 1000)

                # Extract text
                text = response.text if response.text else ""

                # Try to get token counts from usage metadata
                tokens_input = 0
                tokens_output = 0
                token_source = "api"

                if hasattr(response, 'usage_metadata') and response.usage_metadata:
                    tokens_input = getattr(response.usage_metadata, 'prompt_token_count', 0) or 0
                    tokens_output = getattr(response.usage_metadata, 'candidates_token_count', 0) or 0

                # Fallback to estimation if API didn't return token counts
                if tokens_input == 0 or tokens_output == 0:
                    token_source = "estimated"
                    full_prompt = system_instruction + "\n" + prompt
                    if tokens_input == 0:
                        tokens_input = estimate_tokens_from_text(full_prompt)
                    if tokens_output == 0:
                        tokens_output = estimate_tokens_from_text(text)

                # Update totals based on source
                self.total_calls += 1
                if token_source == "api":
                    self.total_tokens_input_actual += tokens_input
                    self.total_tokens_output_actual += tokens_output
                    self.calls_with_actual_tokens += 1
                else:
                    self.total_tokens_input_estimated += tokens_input
                    self.total_tokens_output_estimated += tokens_output
                    self.calls_with_estimated_tokens += 1

                # Calculate cost using model-specific pricing
                pricing = get_model_pricing(self.model)
                cost = (tokens_input / 1_000_000 * pricing["input"] +
                        tokens_output / 1_000_000 * pricing["output"])
                self.total_cost_usd += cost

                metadata = {
                    "latency_ms": latency_ms,
                    "tokens_input": tokens_input,
                    "tokens_output": tokens_output,
                    "cost_estimate_usd": cost,
                    "token_source": token_source,
                    "model": self.model,
                    "retries": attempt,
                }

                if self.verbose:
                    retry_info = f" (retry {attempt})" if attempt > 0 else ""
                    source_indicator = "" if token_source == "api" else " [est]"
                    print(f"[Gemini] Call {self.total_calls}{retry_info}: {latency_ms}ms, "
                          f"{tokens_input}+{tokens_output} tokens{source_indicator}, ${cost:.4f}")

                return text, metadata

            except Exception as e:
                last_error = e
                self.total_retries += 1

                if self.verbose:
                    print(f"[Gemini] Error on attempt {attempt + 1}: {e}")

                # Check if we should retry
                if attempt < self.max_retries and self._is_retryable_error(e):
                    self._wait_with_backoff(attempt)
                else:
                    # Non-retryable error or max retries reached
                    break

        # All retries failed
        raise RuntimeError(f"Gemini API call failed after {self.max_retries + 1} attempts: {last_error}")

    def get_stats(self) -> Dict[str, Any]:
        """Get client usage statistics with actual vs estimated token breakdown."""
        total_tokens_input = self.total_tokens_input_actual + self.total_tokens_input_estimated
        total_tokens_output = self.total_tokens_output_actual + self.total_tokens_output_estimated

        return {
            "total_calls": self.total_calls,
            "total_retries": self.total_retries,
            "total_tokens_input": total_tokens_input,
            "total_tokens_output": total_tokens_output,
            "total_cost_usd": self.total_cost_usd,
            "retry_rate": self.total_retries / max(1, self.total_calls),
            # Detailed token tracking
            "tokens_input_actual": self.total_tokens_input_actual,
            "tokens_input_estimated": self.total_tokens_input_estimated,
            "tokens_output_actual": self.total_tokens_output_actual,
            "tokens_output_estimated": self.total_tokens_output_estimated,
            "calls_with_actual_tokens": self.calls_with_actual_tokens,
            "calls_with_estimated_tokens": self.calls_with_estimated_tokens,
            "model": self.model,
        }


# =============================================================================
# JSON Parsing Utilities
# =============================================================================

def extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Extract JSON from text, handling markdown code blocks."""
    # Try to find JSON in markdown code block
    code_block_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
    if code_block_match:
        text = code_block_match.group(1)

    # Find JSON object boundaries
    text = text.strip()
    start_idx = text.find("{")
    end_idx = text.rfind("}")

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        json_str = text[start_idx:end_idx + 1]
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            pass

    return None


def safe_get(d: Dict, *keys, default=None):
    """Safely get nested dictionary values with fallback keys."""
    for key in keys:
        if isinstance(d, dict) and key in d:
            return d[key]
    return default


def _log_parse_failure(
    response_text: str,
    agent_type: str,
    error: Optional[Exception] = None,
    verbose: bool = False,
) -> None:
    """
    Log detailed information about a parse failure.

    Args:
        response_text: The raw response that failed to parse
        agent_type: The type of agent (e.g., "PLANNER", "ANALYST")
        error: The exception that occurred (if any)
        verbose: If True, write full response to debug file
    """
    # Truncate for display (avoid flooding console)
    snippet_len = 500
    snippet = response_text[:snippet_len]
    if len(response_text) > snippet_len:
        snippet += f"... [{len(response_text) - snippet_len} more chars]"

    print(f"[{agent_type}] Parse error: {error if error else 'Failed to extract valid JSON'}")
    print(f"[{agent_type}] Response snippet:")
    print(snippet)

    # Optionally write full response to debug file
    if verbose:
        import tempfile
        import os
        debug_dir = tempfile.gettempdir()
        debug_path = os.path.join(debug_dir, f"debug_{agent_type.lower()}_{int(time.time())}.txt")
        try:
            with open(debug_path, "w", encoding="utf-8") as f:
                f.write(f"Agent: {agent_type}" + chr(10))
                f.write(f"Timestamp: {datetime.now().isoformat()}" + chr(10))
                f.write(f"Error: {error}" + chr(10))
                f.write(f"Response length: {len(response_text)}" + chr(10))
                f.write("-" * 50 + chr(10))
                # Limit file size to 50KB to avoid disk issues
                max_size = 50_000
                f.write(response_text[:max_size])
                if len(response_text) > max_size:
                    f.write(chr(10) + f"... [truncated {len(response_text) - max_size} chars]")
            print(f"[{agent_type}] Full response saved to {debug_path}")
        except Exception as write_err:
            print(f"[{agent_type}] Failed to write debug file: {write_err}")


def _parse_json_with_logging(
    response_text: str,
    agent_type: str,
    verbose: bool = False,
) -> Optional[Dict[str, Any]]:
    """
    Parse JSON from response text with detailed error logging.

    Args:
        response_text: The raw response text
        agent_type: The type of agent for logging
        verbose: If True, write full response to debug file on failure

    Returns:
        Parsed JSON dict or None on failure
    """
    try:
        result = extract_json(response_text)
        if result is None:
            _log_parse_failure(response_text, agent_type, None, verbose)
        return result
    except Exception as e:
        _log_parse_failure(response_text, agent_type, e, verbose)
        return None


def _run_with_parse_retry(
    generate_fn,
    parse_fn,
    agent_type: str,
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[str, Optional[Any], Dict[str, Any]]:
    """
    Run an agent call with retry on parse failures.

    This wrapper retries the API call if the response fails to parse,
    up to max_parse_retries times. API errors (rate limits, etc.) are
    handled separately by the GeminiAgentClient.

    Args:
        generate_fn: Callable that returns (response_text, metadata)
        parse_fn: Callable that takes response_text and returns parsed output or None
        agent_type: Agent name for logging (e.g., "PLANNER")
        max_parse_retries: Max retries for parse failures (default 2)
        verbose: Enable verbose logging

    Returns:
        Tuple of (final_response_text, parsed_output_or_none, aggregated_metadata)
    """
    all_metadata = []
    last_response = ""

    for attempt in range(max_parse_retries + 1):
        response, metadata = generate_fn()
        last_response = response
        all_metadata.append(metadata)

        output = parse_fn(response)
        if output is not None:
            # Success - aggregate metadata
            agg_metadata = _aggregate_metadata(all_metadata, attempt)
            return response, output, agg_metadata

        # Parse failed
        if attempt < max_parse_retries:
            print(f"[{agent_type}] Parse failed (attempt {attempt + 1}/{max_parse_retries + 1}), retrying...")
            _log_parse_failure(response, agent_type, None, verbose)
            time.sleep(1 * (attempt + 1))  # Simple backoff
        else:
            # Final attempt failed
            _log_parse_failure(response, agent_type, None, verbose)

    # All retries exhausted
    agg_metadata = _aggregate_metadata(all_metadata, max_parse_retries)
    return last_response, None, agg_metadata


def _aggregate_metadata(metadata_list: List[Dict[str, Any]], parse_retries: int) -> Dict[str, Any]:
    """Aggregate metadata from multiple attempts."""
    if not metadata_list:
        return {"latency_ms": 0, "tokens_input": 0, "tokens_output": 0, "cost_estimate_usd": 0.0, "parse_retries": 0}

    total_latency = sum(m.get("latency_ms", 0) for m in metadata_list)
    total_input = sum(m.get("tokens_input", 0) for m in metadata_list)
    total_output = sum(m.get("tokens_output", 0) for m in metadata_list)
    total_cost = sum(m.get("cost_estimate_usd", m.get("cost_usd", 0.0)) for m in metadata_list)

    return {
        "latency_ms": total_latency,
        "tokens_input": total_input,
        "tokens_output": total_output,
        "cost_estimate_usd": total_cost,
        "cost_usd": total_cost,
        "parse_retries": parse_retries,
        "api_retries": sum(m.get("retries", 0) for m in metadata_list),
    }


# =============================================================================
# Agent Implementations
# =============================================================================

def build_planner_prompt(
    market_title: str,
    market_description: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    notable_moves: List[Dict],
    query_budget: int,
    previous_feedback: Optional[str] = None,
) -> str:
    """Build the prompt for the planner agent."""
    start, end = time_range

    prompt = f"""MARKET ANALYSIS REQUEST

Market: {market_title}

MARKET DATA WINDOW:
- Start: {start}
- End: {end}

CRITICAL: RESEARCH CUTOFF DATE IS {research_cutoff}
ALL research must use sources dated BEFORE {research_cutoff}.
We are simulating a prediction made as of {research_cutoff}.
DO NOT use any information that would not have been available on {research_cutoff}.

MARKET DESCRIPTION:
{market_description[:2000]}

NOTABLE PRICE MOVES (significant swings to investigate):
"""

    if notable_moves:
        for m in notable_moves[:5]:
            date = m.get("date", "unknown")
            move_pct = m.get("move_pct", 0) * 100
            prompt += f"- {date}: {move_pct:+.1f}%\n"
    else:
        prompt += "- No significant moves detected\n"

    prompt += f"""
QUERY BUDGET: {query_budget} sub-questions maximum

YOUR TASK:
1. FIRST: Search to identify what TYPE of market this is
2. THEN: Research how similar outcomes have been predicted in the past
3. IDENTIFY: What systematic forecast errors exist in this domain?
4. CREATE: Sub-questions that mix HISTORICAL context with CURRENT evidence
"""

    if previous_feedback:
        prompt += f"""
FEEDBACK FROM PREVIOUS ITERATION (address these gaps):
{previous_feedback}
"""

    prompt += """
Return your analysis as JSON with marketType, domainContext, and subQuestions."""

    return prompt


def parse_planner_response(text: str) -> Optional[PlannerOutput]:
    """Parse planner agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        sub_questions = []
        raw_questions = safe_get(parsed, "subQuestions", "sub_questions", default=[])
        for i, q in enumerate(raw_questions):
            sub_questions.append(SubQuestion(
                id=safe_get(q, "id", default=f"q{i+1}"),
                question=safe_get(q, "question", default=""),
                priority=safe_get(q, "priority", default="medium"),
                target_date=safe_get(q, "targetDate", "target_date"),
                reasoning=safe_get(q, "reasoning"),
            ))

        return PlannerOutput(
            market_type=safe_get(parsed, "marketType", "market_type"),
            domain_context=safe_get(parsed, "domainContext", "domain_context"),
            sub_questions=sub_questions,
            focus_notes=safe_get(parsed, "focusNotes", "focus_notes", default=""),
            reasoning=safe_get(parsed, "reasoning", default=""),
            confidence=safe_get(parsed, "confidence", default=0.5),
        )
    except Exception:
        return None


def run_planner(
    client: GeminiAgentClient,
    market_title: str,
    market_description: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    notable_moves: List[Dict],
    query_budget: int = 5,
    previous_feedback: Optional[str] = None,
    iteration: int = 1,
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[Optional[PlannerOutput], LLMCallLog]:
    """Run the planner agent with automatic retry on parse failures."""
    prompt = build_planner_prompt(
        market_title, market_description, time_range, research_cutoff,
        notable_moves, query_budget, previous_feedback
    )

    def generate_fn():
        return client.generate(
            prompt,
            PLANNER_SYSTEM_PROMPT,
            enable_grounding=True,
            temperature=0.7,
        )

    response, output, metadata = _run_with_parse_retry(
        generate_fn,
        parse_planner_response,
        "PLANNER",
        max_parse_retries=max_parse_retries,
        verbose=verbose,
    )

    log = LLMCallLog(
        call_id=f"iter{iteration}_planner",
        agent="planner",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata.get("cost_estimate_usd", metadata.get("cost_usd", 0.0)),
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse planner response after {max_parse_retries + 1} attempts",
    )

    return output, log


def build_analyst_prompt(
    market_title: str,
    sub_questions: List[SubQuestion],
    time_range: Tuple[str, str],
    research_cutoff: str,
    seen_urls: Optional[Set[str]] = None,
) -> str:
    """Build the prompt for the analyst agent."""
    start, end = time_range

    prompt = f"""RESEARCH TASK

Market: {market_title}
Market Data Window: {start} to {end}

RESEARCH CUTOFF DATE: {research_cutoff}
CRITICAL CONSTRAINT: Only use sources published BEFORE {research_cutoff}.

SUB-QUESTIONS TO RESEARCH:
"""

    for i, q in enumerate(sub_questions):
        prompt += f"{i+1}. [{q.id}] {q.question}\n"
        prompt += f"   Priority: {q.priority}\n"
        if q.target_date:
            prompt += f"   Target date: {q.target_date}\n"
        prompt += "\n"

    # Add previously cited sources to avoid re-citing them
    if seen_urls and len(seen_urls) > 0:
        prompt += """
ALREADY CITED SOURCES (do NOT re-cite these - find NEW sources instead):
"""
        # Limit to 20 URLs to avoid prompt bloat
        for url in list(seen_urls)[:20]:
            prompt += f"- {url}\n"
        if len(seen_urls) > 20:
            prompt += f"... and {len(seen_urls) - 20} more\n"
        prompt += "\n"

    prompt += """
For each question:
1. Search for relevant evidence
2. Verify source dates are before cutoff
3. Score source credibility
4. Synthesize findings with confidence

Return your analysis as JSON."""

    return prompt


def parse_analyst_response(text: str) -> Optional[AnalystOutput]:
    """Parse analyst agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        answers = []
        raw_answers = safe_get(parsed, "answers", default=[])
        for a in raw_answers:
            citations = []
            for c in safe_get(a, "citations", default=[]):
                citations.append(Citation(
                    url=safe_get(c, "url", default=""),
                    title=safe_get(c, "title"),
                    author=safe_get(c, "author"),
                    outlet=safe_get(c, "outlet"),
                    publish_date=safe_get(c, "publishDate", "publish_date"),
                ))

            answers.append(AnswerClaim(
                question_id=safe_get(a, "questionId", "question_id", default=""),
                answer=safe_get(a, "answer", default=""),
                confidence=safe_get(a, "confidence", default=0.5),
                citations=citations,
                evidence_summary=safe_get(a, "evidenceSummary", "evidence_summary", default=""),
                reasoning=safe_get(a, "reasoning", default=""),
                potential_issues=safe_get(a, "potentialIssues", "potential_issues", default=[]),
            ))

        all_sources = []
        for s in safe_get(parsed, "allSourcesUsed", "all_sources_used", default=[]):
            all_sources.append(Citation(
                url=safe_get(s, "url", default=""),
                title=safe_get(s, "title"),
            ))

        return AnalystOutput(
            answers=answers,
            all_sources_used=all_sources,
            overall_confidence=safe_get(parsed, "overallConfidence", "overall_confidence", default=0.5),
            reasoning=safe_get(parsed, "reasoning", default=""),
        )
    except Exception:
        return None


def run_analyst(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
    seen_urls: Optional[Set[str]] = None,
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[Optional[AnalystOutput], LLMCallLog]:
    """Run the analyst agent with automatic retry on parse failures."""
    prompt = build_analyst_prompt(market_title, sub_questions, time_range, research_cutoff, seen_urls)

    def generate_fn():
        return client.generate(
            prompt,
            ANALYST_SYSTEM_PROMPT,
            enable_grounding=True,
            temperature=0.5,
        )

    response, output, metadata = _run_with_parse_retry(
        generate_fn,
        parse_analyst_response,
        "ANALYST",
        max_parse_retries=max_parse_retries,
        verbose=verbose,
    )

    log = LLMCallLog(
        call_id=f"iter{iteration}_analyst",
        agent="analyst",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata.get("cost_estimate_usd", metadata.get("cost_usd", 0.0)),
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse analyst response after {max_parse_retries + 1} attempts",
    )

    return output, log


def build_advocate_prompt(
    market_title: str,
    sub_questions: List[SubQuestion],
    position: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    seen_urls: Optional[Set[str]] = None,
) -> str:
    """Build the prompt for an advocate agent."""
    start, end = time_range

    prompt = f"""MARKET TO ANALYZE
Title: {market_title}

YOUR POSITION: Argue that this market resolves {position}

RESEARCH WINDOW: {start} to {end}
CRITICAL: Research cutoff is {research_cutoff}. You MUST NOT use any sources published after this date.

CONTEXT - Key questions identified by the Planner:
"""

    for i, q in enumerate(sub_questions):
        prompt += f"{i+1}. [{q.priority}] {q.question}\n"

    # Add previously cited sources to avoid re-citing them
    if seen_urls and len(seen_urls) > 0:
        prompt += """
ALREADY CITED SOURCES (do NOT re-cite these - find NEW sources instead):
"""
        # Limit to 20 URLs to avoid prompt bloat
        for url in list(seen_urls)[:20]:
            prompt += f"- {url}\n"
        if len(seen_urls) > 20:
            prompt += f"... and {len(seen_urls) - 20} more\n"

    prompt += f"""
YOUR TASK:
Build the strongest possible case that this market resolves {position}.
- Search for evidence that supports {position}
- Find historical precedents where similar situations resolved {position}
- Anticipate what an advocate for the opposite outcome would argue
- Prepare rebuttals for those counter-arguments
- Be honest about the weakest part of your case

Remember:
- You are BIASED BY DESIGN - that's your job
- But don't fabricate evidence - cite real sources
- Acknowledge your weakest point honestly
- The strongest arguments address the opponent's best points, not straw men

Return your argument as valid JSON."""

    return prompt


def parse_advocate_response(text: str, position: str) -> Optional[AdvocateOutput]:
    """Parse advocate agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        primary_evidence = []
        for e in safe_get(parsed, "primaryEvidence", "primary_evidence", default=[]):
            source_data = safe_get(e, "source", default={})
            source = Citation(
                url=safe_get(source_data, "url", default=safe_get(e, "url", default="")),
                title=safe_get(source_data, "title", default=safe_get(e, "title")),
                author=safe_get(source_data, "author"),
                outlet=safe_get(source_data, "outlet"),
                publish_date=safe_get(source_data, "publishDate", "publish_date"),
            )
            primary_evidence.append(AdvocateEvidence(
                claim=safe_get(e, "claim", default=""),
                source=source,
                strength=safe_get(e, "strength", default=0.5),
                reasoning=safe_get(e, "reasoning", default=""),
            ))

        all_sources = []
        for s in safe_get(parsed, "allSourcesUsed", "all_sources_used", default=[]):
            all_sources.append(Citation(
                url=safe_get(s, "url", default=""),
                title=safe_get(s, "title"),
            ))

        # Also add sources from evidence if allSourcesUsed is empty
        if not all_sources:
            seen_urls = set()
            for e in primary_evidence:
                if e.source.url and e.source.url not in seen_urls:
                    seen_urls.add(e.source.url)
                    all_sources.append(e.source)

        return AdvocateOutput(
            position=safe_get(parsed, "position", default=position),
            core_argument=safe_get(parsed, "coreArgument", "core_argument", default=""),
            primary_evidence=primary_evidence,
            historical_precedent=safe_get(parsed, "historicalPrecedent", "historical_precedent", default=""),
            anticipated_counterarguments=safe_get(parsed, "anticipatedCounterarguments", "anticipated_counterarguments", default=[]),
            rebuttals=safe_get(parsed, "rebuttals", default=[]),
            weakest_point=safe_get(parsed, "weakestPoint", "weakest_point", default=""),
            confidence=safe_get(parsed, "confidence", default=0.5),
            reasoning=safe_get(parsed, "reasoning", default=""),
            all_sources_used=all_sources,
        )
    except Exception:
        return None


def run_advocate(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    position: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
    seen_urls: Optional[Set[str]] = None,
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[Optional[AdvocateOutput], LLMCallLog]:
    """Run an advocate agent (YES or NO) with automatic retry on parse failures."""
    prompt = build_advocate_prompt(market_title, sub_questions, position, time_range, research_cutoff, seen_urls)
    system_prompt = ADVOCATE_YES_SYSTEM_PROMPT if position == "YES" else ADVOCATE_NO_SYSTEM_PROMPT
    agent_type = f"advocate_{position.lower()}"

    def generate_fn():
        return client.generate(
            prompt,
            system_prompt,
            enable_grounding=True,
            temperature=0.7,
        )

    response, output, metadata = _run_with_parse_retry(
        generate_fn,
        lambda text: parse_advocate_response(text, position),
        agent_type.upper(),
        max_parse_retries=max_parse_retries,
        verbose=verbose,
    )

    log = LLMCallLog(
        call_id=f"iter{iteration}_{agent_type}",
        agent=agent_type,
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata.get("cost_estimate_usd", metadata.get("cost_usd", 0.0)),
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse {agent_type} response after {max_parse_retries + 1} attempts",
    )

    return output, log


def build_verifier_prompt(
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    advocate_yes_output: Optional[AdvocateOutput],
    advocate_no_output: Optional[AdvocateOutput],
    wayback_context: str = "",
) -> str:
    """Build the prompt for the verifier agent."""
    start, end = time_range
    has_debate = advocate_yes_output and advocate_no_output

    prompt = f"""VERIFICATION {"AND DEBATE JUDGING " if has_debate else ""}TASK

Market: {market_title}
Market Data Window: {start} to {end}

CRITICAL: RESEARCH CUTOFF DATE IS {research_cutoff}
ANY source after {research_cutoff} is a CRITICAL issue (data leakage).

=== NEUTRAL ANALYST FINDINGS ===
Overall Confidence: {analyst_output.overall_confidence:.0%}
Answers:
"""

    for a in analyst_output.answers:
        prompt += f"- [{a.question_id}] {a.answer[:200]}... (confidence: {a.confidence:.0%})\n"

    if has_debate:
        prompt += f"""
=== ADVOCATE FOR YES ===
Core Argument: {advocate_yes_output.core_argument[:300]}...
Confidence: {advocate_yes_output.confidence:.0%}
Weakest Point: {advocate_yes_output.weakest_point[:200]}...

=== ADVOCATE FOR NO ===
Core Argument: {advocate_no_output.core_argument[:300]}...
Confidence: {advocate_no_output.confidence:.0%}
Weakest Point: {advocate_no_output.weakest_point[:200]}...

YOUR TASKS:
1. VERIFY ALL SOURCES from analyst and BOTH advocates
2. VERIFY AUTHOR CREDIBILITY
3. FIND CONTRADICTIONS and search for missing evidence
4. JUDGE THE DEBATE - which advocate has stronger VERIFIED evidence?
5. IDENTIFY GAPS in all analyses
"""
    else:
        prompt += """
YOUR TASKS:
1. Check EVERY source URL - is it dated before the cutoff?
2. Verify author credibility
3. Search for CONTRADICTING evidence
4. Evaluate whether evidence supports conclusions
5. Identify gaps in the analysis
"""

    # Add Wayback validation context if provided
    if wayback_context:
        prompt += f"""
{wayback_context}
"""

    prompt += """
Be thorough and adversarial. Find the weaknesses in EVERYONE's arguments.

Return your verification as JSON."""

    return prompt


def parse_verifier_response(text: str) -> Optional[VerifierOutput]:
    """Parse verifier agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        issues = []
        for i in safe_get(parsed, "issues", default=[]):
            issues.append(Issue(
                type=safe_get(i, "type", default="gap"),
                severity=safe_get(i, "severity", default="minor"),
                description=safe_get(i, "description", default=""),
                affected_claims=safe_get(i, "affectedClaims", "affected_claims", default=[]),
                recommendation=safe_get(i, "recommendation"),
            ))

        debate_assessment = None
        raw_debate = safe_get(parsed, "debateAssessment", "debate_assessment")
        if raw_debate:
            debate_assessment = DebateAssessment(
                advocate_yes_strength=safe_get(raw_debate, "advocateYesStrength", "advocate_yes_strength", default=0.5),
                advocate_yes_strongest_point=safe_get(raw_debate, "advocateYesStrongestPoint", "advocate_yes_strongest_point", default=""),
                advocate_yes_weakest_point=safe_get(raw_debate, "advocateYesWeakestPoint", "advocate_yes_weakest_point", default=""),
                advocate_no_strength=safe_get(raw_debate, "advocateNoStrength", "advocate_no_strength", default=0.5),
                advocate_no_strongest_point=safe_get(raw_debate, "advocateNoStrongestPoint", "advocate_no_strongest_point", default=""),
                advocate_no_weakest_point=safe_get(raw_debate, "advocateNoWeakestPoint", "advocate_no_weakest_point", default=""),
                winner=safe_get(raw_debate, "winner", default="TIE"),
                reasoning=safe_get(raw_debate, "reasoning", default=""),
            )

        adjusted_confidences = {}
        raw_conf = safe_get(parsed, "adjustedConfidences", "adjusted_confidences", default={})
        for k, v in raw_conf.items():
            adjusted_confidences[k] = float(v) if isinstance(v, (int, float)) else 0.5

        return VerifierOutput(
            issues=issues,
            debate_assessment=debate_assessment,
            adjusted_confidences=adjusted_confidences,
            overall_adjusted_confidence=safe_get(parsed, "overallAdjustedConfidence", "overall_adjusted_confidence", default=0.5),
            missing_evidence_needs=safe_get(parsed, "missingEvidenceNeeds", "missing_evidence_needs", default=[]),
            reasoning=safe_get(parsed, "reasoning", default=""),
        )
    except Exception:
        return None


def run_verifier(
    client: GeminiAgentClient,
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    advocate_yes_output: Optional[AdvocateOutput],
    advocate_no_output: Optional[AdvocateOutput],
    iteration: int = 1,
    wayback_context: str = "",
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[Optional[VerifierOutput], LLMCallLog]:
    """Run the verifier agent with automatic retry on parse failures."""
    prompt = build_verifier_prompt(
        market_title, time_range, research_cutoff,
        analyst_output, advocate_yes_output, advocate_no_output,
        wayback_context=wayback_context,
    )

    def generate_fn():
        return client.generate(
            prompt,
            VERIFIER_SYSTEM_PROMPT,
            enable_grounding=True,
            temperature=0.5,
        )

    response, output, metadata = _run_with_parse_retry(
        generate_fn,
        parse_verifier_response,
        "VERIFIER",
        max_parse_retries=max_parse_retries,
        verbose=verbose,
    )

    log = LLMCallLog(
        call_id=f"iter{iteration}_verifier",
        agent="verifier",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata.get("cost_estimate_usd", metadata.get("cost_usd", 0.0)),
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse verifier response after {max_parse_retries + 1} attempts",
    )

    return output, log


def build_synthesizer_prompt(
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    verifier_output: VerifierOutput,
    iteration: int,
    max_iterations: int,
    confidence_threshold: float,
) -> str:
    """Build the prompt for the synthesizer agent."""
    start, end = time_range

    prompt = f"""SYNTHESIS TASK

Market: {market_title}
Iteration: {iteration} of {max_iterations}
Confidence Threshold: {confidence_threshold}
Market Data Window: {start} to {end}
Research Cutoff: {research_cutoff}

=== ANALYST FINDINGS ===
Overall Confidence: {analyst_output.overall_confidence:.0%}
"""

    for a in analyst_output.answers[:3]:
        prompt += f"- {a.answer[:200]}...\n"

    prompt += f"""
=== VERIFIER ASSESSMENT ===
Adjusted Confidence: {verifier_output.overall_adjusted_confidence:.0%}
Issues Found: {len(verifier_output.issues)}
"""

    for i in verifier_output.issues[:3]:
        prompt += f"- [{i.severity}] {i.description[:100]}...\n"

    if verifier_output.debate_assessment:
        da = verifier_output.debate_assessment
        prompt += f"""
=== DEBATE RESULTS (IMPORTANT) ===
Advocate YES strength: {da.advocate_yes_strength:.0%}
  - Strongest point: {da.advocate_yes_strongest_point[:100]}...
Advocate NO strength: {da.advocate_no_strength:.0%}
  - Strongest point: {da.advocate_no_strongest_point[:100]}...

DEBATE WINNER: {da.winner}
Reasoning: {da.reasoning[:200]}...

NOTE: The debate winner indicates which side had BETTER VERIFIED EVIDENCE.
Weight this heavily in your prediction direction.
"""

    prompt += f"""
=== DECISION REQUIRED ===
- Verifier's adjusted confidence: {verifier_output.overall_adjusted_confidence:.0%}
- Threshold for commit: {confidence_threshold:.0%}
- Iterations remaining: {max_iterations - iteration}

{
    "Confidence meets threshold - you may COMMIT if reasoning is sound."
    if verifier_output.overall_adjusted_confidence >= confidence_threshold
    else "Confidence below threshold - consider RETRY if there are clear gaps to fill, or COMMIT with caveats if no clear improvement path."
}
"""

    if verifier_output.missing_evidence_needs:
        prompt += f"""
Missing evidence identified:
"""
        for e in verifier_output.missing_evidence_needs[:3]:
            prompt += f"- {e}\n"

    prompt += """
Return your synthesis as JSON with prediction, probability, confidence, and decision (COMMIT or RETRY)."""

    return prompt


def parse_synthesizer_response(text: str) -> Optional[SynthesizerOutput]:
    """Parse synthesizer agent response."""
    parsed = extract_json(text)
    if not parsed:
        return None

    try:
        key_evidence = []
        for ke in safe_get(parsed, "keyEvidence", "key_evidence", default=[]):
            key_evidence.append(KeyEvidence(
                claim=safe_get(ke, "claim", default=""),
                source=safe_get(ke, "source", default=""),
                weight=safe_get(ke, "weight", default=0.5),
            ))

        return SynthesizerOutput(
            prediction=safe_get(parsed, "prediction", default=""),
            probability=safe_get(parsed, "probability", default=0.5),
            confidence=safe_get(parsed, "confidence", default=0.5),
            decision=safe_get(parsed, "decision", default="COMMIT"),
            reasoning=safe_get(parsed, "reasoning", default=""),
            key_evidence=key_evidence,
            caveats=safe_get(parsed, "caveats", default=[]),
            retry_focus=safe_get(parsed, "retryFocus", "retry_focus"),
        )
    except Exception:
        return None


def run_synthesizer(
    client: GeminiAgentClient,
    market_title: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    analyst_output: AnalystOutput,
    verifier_output: VerifierOutput,
    iteration: int,
    max_iterations: int,
    confidence_threshold: float,
    max_parse_retries: int = 2,
    verbose: bool = False,
) -> Tuple[Optional[SynthesizerOutput], LLMCallLog]:
    """Run the synthesizer agent with automatic retry on parse failures."""
    prompt = build_synthesizer_prompt(
        market_title, time_range, research_cutoff,
        analyst_output, verifier_output,
        iteration, max_iterations, confidence_threshold
    )

    def generate_fn():
        return client.generate(
            prompt,
            SYNTHESIZER_SYSTEM_PROMPT,
            enable_grounding=True,
            temperature=0.5,
        )

    response, output, metadata = _run_with_parse_retry(
        generate_fn,
        parse_synthesizer_response,
        "SYNTHESIZER",
        max_parse_retries=max_parse_retries,
        verbose=verbose,
    )

    log = LLMCallLog(
        call_id=f"iter{iteration}_synthesizer",
        agent="synthesizer",
        timestamp=datetime.now().isoformat(),
        iteration=iteration,
        latency_ms=metadata["latency_ms"],
        tokens_input=metadata["tokens_input"],
        tokens_output=metadata["tokens_output"],
        cost_estimate_usd=metadata.get("cost_estimate_usd", metadata.get("cost_usd", 0.0)),
        raw_response=response[:2000],
        parse_error=None if output else f"Failed to parse synthesizer response after {max_parse_retries + 1} attempts",
    )

    return output, log


# =============================================================================
# Async Agent Runners (for true parallel execution)
# =============================================================================

import asyncio


async def run_analyst_async(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
    seen_urls: Optional[Set[str]] = None,
) -> Tuple[Optional[AnalystOutput], LLMCallLog]:
    """Async version of run_analyst using asyncio.to_thread()."""
    return await asyncio.to_thread(
        run_analyst,
        client, market_title, sub_questions, time_range, research_cutoff, iteration, seen_urls
    )


async def run_advocate_async(
    client: GeminiAgentClient,
    market_title: str,
    sub_questions: List[SubQuestion],
    position: str,
    time_range: Tuple[str, str],
    research_cutoff: str,
    iteration: int = 1,
    seen_urls: Optional[Set[str]] = None,
) -> Tuple[Optional[AdvocateOutput], LLMCallLog]:
    """Async version of run_advocate using asyncio.to_thread()."""
    return await asyncio.to_thread(
        run_advocate,
        client, market_title, sub_questions, position, time_range, research_cutoff, iteration, seen_urls
    )


# =============================================================================
# LESSONS LEARNED
# =============================================================================
# 2026-01-21 Agent Implementation:
#
# PORTING FROM TYPESCRIPT:
# 1. Simplified dataclasses vs TypeScript interfaces
# 2. Used @dataclass with field(default_factory=list) for mutable defaults
# 3. JSON parsing handles both camelCase and snake_case keys
#
# API INTEGRATION:
# 1. Gemini grounding via google_search tool works well
# 2. Token counts from usage_metadata may be None - handle gracefully
# 3. Temperature: lower (0.5) for analyst/verifier, higher (0.7) for advocates
#
# PROMPT ENGINEERING:
# 1. Cutoff date enforcement is repeated multiple times - works better
# 2. JSON output format must be explicit in prompts
# 3. Examples in prompts help but increase token usage
#
# ERROR HANDLING:
# 1. All parse functions return Optional - caller handles None
# 2. LLMCallLog captures raw response for debugging
# 3. parse_error field tracks parsing failures
#
# 2026-01-22 Token Cost Tracking Enhancement:
#
# ACCURATE PRICING:
# 1. Added GEMINI_PRICING dict with model-specific costs (per 1M tokens)
# 2. Pricing source: https://ai.google.dev/gemini-api/docs/pricing
# 3. DEFAULT_PRICING fallback for unknown models uses gemini-2.0-flash rates
#
# TOKEN TRACKING:
# 1. Primary: use usage_metadata from API response when available
# 2. Fallback: estimate_tokens_from_text() uses ~4 chars/token heuristic
# 3. LLMCallLog.token_source field tracks whether "api" or "estimated"
# 4. GeminiAgentClient tracks actual vs estimated tokens separately
#
# COST CALCULATION:
# 1. get_model_pricing() handles model name normalization (-001, -latest, etc)
# 2. Cost formula: (input_tokens / 1M * input_price) + (output_tokens / 1M * output_price)
# 3. get_stats() returns both aggregated totals and actual/estimated breakdown
#
# COMPATIBILITY:
# 1. Kept cost_estimate_usd field name for backward compatibility
# 2. metadata dict includes both cost_estimate_usd and token_source
#
# 2026-01-22 Better Error Messages and Retry Logic:
#
# PARSE ERROR LOGGING (_log_parse_failure):
# 1. Shows first 500 chars of response as snippet
# 2. When verbose=True, writes full response to temp file (max 50KB)
# 3. Debug files in temp dir: debug_{agent_type}_{timestamp}.txt
#
# RETRY ON PARSE FAILURES (_run_with_parse_retry):
# 1. Wraps generate_fn and parse_fn with automatic retry
# 2. max_parse_retries=2 by default (3 total attempts)
# 3. Simple backoff: 1s, 2s, 3s between retries
# 4. Aggregates metadata (latency, tokens, cost) across all attempts
# 5. Does NOT retry API errors (rate limits handled by GeminiAgentClient)
#
# RUNNER FUNCTION CHANGES:
# 1. All run_* functions now accept max_parse_retries and verbose params
# 2. Error messages include attempt count on failure
# 3. Metadata includes parse_retries count for debugging
#
# 2026-01-22 Async Agent Runners:
#
# IMPLEMENTATION:
# 1. Added async versions of all agent runners (run_*_async functions)
# 2. Each async function uses asyncio.to_thread() to wrap blocking Gemini calls
# 3. This enables true parallel execution when used with asyncio.gather()
# 4. Sync versions kept for backward compatibility
#
# USAGE:
# 1. Pipeline uses asyncio.run(_run_parallel_agents()) for parallel phase
# 2. Analyst + Advocate YES + Advocate NO run concurrently
# 3. seen_urls param enables URL deduplication at prompt level
#
# PERFORMANCE:
# 1. True async enables overlapping API wait times
# 2. 3 parallel agents reduce latency vs sequential execution
# 3. GIL not a bottleneck since calls are I/O-bound (network)
#
# 2026-01-22 Source Deduplication:
# - seen_urls param on build_*_prompt() adds "ALREADY CITED SOURCES" section
# - Capped at 20 URLs to avoid prompt bloat
# - Async variants pass seen_urls through to sync functions
#
